### ISSUE TITLE
Error parsing file

### ISSUE THREAD

**Issue by pedro-tanure-veloso** [hansec/autocomplete-fortran#5]
Hi,

While writing my Fortran code, I keep getting "Error parsing file (...)" and "Script failed" underneath. This happens in every single word I type. What am I doing wrong?

**Comment by hansec** [comment]
Well that certainly shouldn't happen... Please try parsing the file in [debug mode](https://github.com/hansec/autocomplete-fortran/wiki/Debugging-parser-errors) and post the output below. Also, what OS are you using?

**Comment by pedro-tanure-veloso** [comment]
I'm sorry, I'm having issues entering the debug mode. Should I run the code provided in the link in the command prompt (I'm using Windows)? If so, I'm getting an error message like the one below: 
![error](https://cloud.githubusercontent.com/assets/23425381/20333324/6a447f3a-ab77-11e6-8265-5907efbca2c8.jpg)

**Comment by hansec** [comment]
What version of python are you using?

**Comment by hansec** [comment]
Ok, I think you are probably using Python3 which I never tested this with. Can you try the updated parsing script in the [py3_printFix](https://github.com/hansec/autocomplete-fortran/tree/py3_printFix) branch and let me know if that works?

**Comment by Foadsf** [comment]
I also have the exact same issue working on fortran code:

<img width="452" alt="screen shot 2016-12-03 at 15 05 18" src="https://cloud.githubusercontent.com/assets/12762442/20859863/0108378a-b96b-11e6-821e-68498eceb638.png">

I checked my python version with `pyhton -V` and I'm using `Python 2.7.12` although I think python 3 is installed for some other projects I have been working on. 
I saw your suggestion above to use an updated branch, but unfortunately I don't know how should I install this experimental branch. should I download/clone it and then install it with python or nod.js? I would appreciate if you could provide the dummy instructions.
I also found [this](http://stackoverflow.com/questions/38954403/errors-typing-fortran-language-in-atom-text-editor) and [this](http://stackoverflow.com/questions/38944783/error-when-saving-fortran-source-in-atom) stackoverflow posts which sugest that there emight be some issue with the sufixes. it appears that when the code version is not what plugin expects from the sufix the error happens. 


edit(1): I uninstalled and reinstalled the pluging and ti come up with a new type of error. now it gives me a report:

<img width="450" alt="screen shot 2016-12-03 at 15 53 25" src="https://cloud.githubusercontent.com/assets/12762442/20860106/bb572ef2-b970-11e6-96f3-b11acf287209.png">

```json
{
  "core": {
    "disabledPackages": [
      "linter-scspell",
      "symbols-view"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "autocomplete-fortran": {
    "pythonPath": "/Users/foadsf/.atom/packages/autocomplete-fortran/python/parse_fortran.py"
  }
}
```

I tried the button `create issue on the autocomplete-fortran package` but I got this error in my browser: `414 Request-URI Too Large nginx`

<img width="445" alt="screen shot 2016-12-03 at 15 55 06" src="https://cloud.githubusercontent.com/assets/12762442/20860122/07fb7dda-b971-11e6-8c0b-3cab94d28cfd.png">



P.S.
besides, unfortunately there is no feature request feature in github :)) so I mention it here there are several great old projects developed by Netlib (formerly Bell Laboratories) and other companies/research groups, which worth being revived and used. here are some I found interesting:

1. [FTNCHEK](http://www.dsm.fordham.edu/ftnchek/)
2. [floppy](http://www.netlib.org/floppy/)
3. [f90ppr](http://www.ifremer.fr/ditigo/molagnon/fortran90/)
4. [fpt](http://www.simconglobal.com/cgi-local/downloads.php)
5. [fortrancheckIDE](http://www.forcheck.nl/)
6. [Cleanscape FortranLint](http://stellar.cleanscape.net/products/downloads/ftpflint.html)
7. [findent](https://sourceforge.net/projects/findent/)

it would be a great idea if you could integrate them into this plugin or having the experience glue them to Atom with other plugins

**Comment by hansec** [comment]
@Foadsf when you run the parsing script from the command line in [debug mode](https://github.com/hansec/autocomplete-fortran/wiki/Debugging-parser-errors) do you get the same Python syntax errors on print statements as above?

**Comment by Foadsf** [comment]
no when I run the command I just get a report assessing my code which seems logical. no errors

**Comment by hansec** [comment]
@Foadsf Ok, your issue is different from this one. It looks like your python path (in the settings for autocomplete-fortran) is set to the parsing script when it should point to your desired python executable. On OS X you should be able to use the default path `/usr/bin/python`. If that change doesn't work please create a [new issue](https://github.com/hansec/autocomplete-fortran/issues/new) with the error you get after making that change. Make sure you close and reopen Atom after changing the path in settings.

**Comment by Foadsf** [comment]
ok, I think I just figured the issue out. first of all sorry for messing up with the default address.  had made mistake putting the parsing script instead of the python itself. I had my python installed using homebrew and it was in `/Library/Frameworks/Python.framework/Versions/2.7/bin/python` not in the default folder. I could find it using the command `which python`
 so by putting the right folder I'm not getting the error anymore. I tried a couple of files and no error seen.

**Comment by Yaphet-Chen** [comment]
Hi, I have the same issue as @ptanure had. My OS is window 10, the version of Python is 2.7(the same as Python 3.5). I also meet some problems when entering debug mode in cmd.

![1485261403 1](https://cloud.githubusercontent.com/assets/16664001/22249280/4ee00182-e27d-11e6-91ca-a66bb1838953.png)

![qq 20170124204005](https://cloud.githubusercontent.com/assets/16664001/22249310/6afc0f14-e27d-11e6-92db-eee657e04738.png)

What weird is that I will get the same syntax error if I copy the parse_fortran.py to D disk.

![qq 20170124214340](https://cloud.githubusercontent.com/assets/16664001/22249500/31919f04-e27e-11e6-97f7-2274bd8f7d0c.png)

So I wonder if the problem is caused by the path? Since it contains space or point?

**Comment by Yaphet-Chen** [comment]
I have the same issue as @ptanure had. My OS is window 10, the version of Python is 2.7(the same as Python 3.5). I also meet some problems when entering debug mode in cmd.
![1485261403 1](https://cloud.githubusercontent.com/assets/16664001/22249280/4ee00182-e27d-11e6-91ca-a66bb1838953.png)
![qq 20170124204005](https://cloud.githubusercontent.com/assets/16664001/22249310/6afc0f14-e27d-11e6-92db-eee657e04738.png)
What weird is that I will get the same synatax error if I copy the parse_fortran.py to D disk.
![qq 20170124214340](https://cloud.githubusercontent.com/assets/16664001/22249500/31919f04-e27e-11e6-97f7-2274bd8f7d0c.png)
So I wonder if the problem is cause by the path? Since it contains space or point?

**Comment by hansec** [comment]
@Yaphet-Chen I just updated things to fix the issue when using Python 3. Try updating the extension and let me know if that fixes things.

As for the path error you get when debugging, it looks like you have the "autocomplete-fortran\python" part of the parser path accidentally repeated (at least it is in the first screenshot).

**Comment by Yaphet-Chen** [comment]
@hansec Sorry for the error path I entered previously. I have updated the autocomplete-fortran package, but it seems that the issue still exists. Currently, all my packages in the atom are up to date.

![_b2up vgis 8cl s jupt6](https://cloud.githubusercontent.com/assets/16664001/22281227/a662944a-e310-11e6-98f8-5f16b3df3ae6.png)

**My Python's version is 3.5.3 and the Python 2 has been uninstalled fully**
![qq 20170125145136](https://cloud.githubusercontent.com/assets/16664001/22281015/5d17a196-e30f-11e6-9e87-f4dbf89352a1.png)

**Bellow is the message in debug mode**
![o1 jjocz5 _k 4x4gvrvg m](https://cloud.githubusercontent.com/assets/16664001/22281073/be095aa8-e30f-11e6-94b9-67e0d2268eb0.png)

**packages installed**
![5s de4 9c9eo a f gjn2f1](https://cloud.githubusercontent.com/assets/16664001/22281096/dc33644c-e30f-11e6-9a38-a8351f9fa756.png)

**python excutable path**
![vh2d8isk5o4 4 26irlye9](https://cloud.githubusercontent.com/assets/16664001/22281324/531aedf4-e311-11e6-8f85-ed59500d966f.png)

Thank you very much for your efforts.

**Comment by hansec** [comment]
Ok, can you check to make sure that Atom is finding your Python executable? After you get the error open the javascript console in the Atom menu "View -> Developer -> Toggle Developer Tools". A pane will open with the developer tools and the Console tab should be selected by default. There should be some output there. If you see something like "... is not recognized as an internal or external command ..." then the Python path is not working. The path you specify needs to be the full path to the Python executable not the containing folder.

If you see something else let me know.

**Comment by Yaphet-Chen** [comment]
There are some errors I got indeed. However, instead of "... is not recognized as an internal or external command ...", it showed up as some messy codes.
![qq 20170126134344](https://cloud.githubusercontent.com/assets/16664001/22321746/2dffd55e-e3d2-11e6-9732-009515eb026e.png)

fortran-provider.coffee:204
![qq 20170126134403](https://cloud.githubusercontent.com/assets/16664001/22321773/5855a52c-e3d2-11e6-977d-85d1ddaaced9.png)

fortran-provider.coffee:249
![qq 20170126134408](https://cloud.githubusercontent.com/assets/16664001/22321781/6aad33c0-e3d2-11e6-82a7-79e7a85f2050.png)

I believe the path I specified is the full path to the Python executable.
![qq 20170126140614](https://cloud.githubusercontent.com/assets/16664001/22321805/91f9d352-e3d2-11e6-8073-dc8c4772bbb1.png)
![qq 20170126140825](https://cloud.githubusercontent.com/assets/16664001/22321806/9234514e-e3d2-11e6-9b97-4698d52b8714.png)

Thank you!

**Comment by hansec** [comment]
Hmmmm, I think the random symbols is an issue with language support. I still think the error is a path issue though. You are only specifying the path to the containing folder. You need to add `\python.exe` onto the end to provide the full path to the actual executable.

**Comment by Yaphet-Chen** [comment]
Hmmm, it does the issue of the path. After I add `\python.exe` onto the end of my previous path, all the errors fixed! :bowtie:
Thank you so much!!!

**Comment by hzxusx** [comment]
Hi, I have just installed this package and encounter this problem. I read the previous posts but found no answer.

When click `rebuild index`
```
Error parsing file ...
Scope stack not empty
```
I looked into the `parse_fortran.py` and found it in function `dump_json` . But I still don't know how to fix it.

When press ` Ctrl+Alt+g`
```
Could not complete operation: Go To Definition
Indexing pending
Could not find definition: ...
```

debug output is as follows
```
program example !!! PROGRAM statement(1)
use test_module !!! USE statement(2)
real :: a !!! VARIABLE statement(4)
type(my_type) :: ex_var !!! VARIABLE statement(5)
end program example !!! END scope(10)
{"objs":{"example::a":{"desc":"REAL","fdef":4,"name":"a","type":6},"example::ex_var":{"desc":"TYPE(my_type)","fdef":5,"name":"ex_var","type":6},"example":{"desc":"PROGRAM","type":1,"mem":["a","ex_var"],"fbound":[1,10],"name":"example","use":[["test_module",[]]]}},"scopes":["example"]}
```

What's the problem?

Some information
```
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Python : 2.7.12
OS : Ubuntu 16.04
```

**Comment by hansec** [comment]
@hzxusx Please create a [new issue](https://github.com/hansec/autocomplete-fortran/issues/new) with this same information. This thread is not meant to be a catch all for all parser errors. When you create the new issue make sure you are running the debug test on the same file that generated the error in Atom. The error you are getting should be produced in debug mode too, so it is strange that your debug output contains no error.
